# Generated by Django 2.1.7 on 2019-02-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='firs_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='salario',
            new_name='salary',
        ),
    ]
